### DISCUSSION TITLE
I want to implement a single VM Power Button....

### DISCUSSION THREAD

**Discussion by KevinKTM** [dougiteixeira/proxmoxve#438] [Q&A] [answered]
I am trying to create a button for each of my vm's. I want to support 3 states - power on, hibernate and long press to power off (with appropriate icons to indicate the 4 states. I did some testing and the power on event has to understand the current state of the vm (sensor.status) in order to issue a either start or restore event. I tried creating a button card with this logic but no workie... excuse my complete lack of understanding how service calls work - trying to give an idea of what I want to do. Not sure if I need to move the the hacs button-card?

```
type: button
name: Proxmox Win11 Power Button
tap_action:
  action: call-service
  service: >
    {% if is_state('sensor.qemu_win11_101_status', 'stopped') %}
      button.qemu_win11_101_start
    {% elif is_state('sensor.qemu_win11_101_status', 'suspended') %}
      button.qemu_win11_101_resume
    {% else %}
      button.qemu_win11_101_hibernate
    {% endif %}
hold_action:
  action: call-service
  service: button.qemu_win11_101_stop
```

**Comment by KevinKTM** [comment]
I'm not getting anywhere on this. I suspect the issue is dynamically changing a button behind a lovelace button?

Can anybody tell me how to make a service call to the integration to turn a vm on or off (in the developer tab)?

**Reply by dougiteixeira** [reply]
See: https://www.home-assistant.io/integrations/button#actions

```
- action: button.press
  target:
    entity_id: button.my_button
 ```

**Comment by KevinKTM** [comment]
How do I use button.press in the context of my lovelace button card code above? I get an error stating tap_action.action is not supported. All I want to do is replace the 4 vm buttons with a single button that covers all states. Tried friggin everything, i'm ready to check out.

**Comment by dougiteixeira** [comment, marked as answer]
Although your question is more about the community forum than the integration, I will try to help you.

I suggest you use a script to simplify things, here is an example.

Code for the script:
```
alias: VM start/stop
description: ""
fields:
  status:
    selector:
      entity:
        domain: sensor
        integration: proxmoxve
    name: Status
    required: true
  start:
    selector:
      entity:
        domain: button
        integration: proxmoxve
    name: Command start
    required: true
  stop:
    selector:
      entity:
        domain: button
        integration: proxmoxve
    name: Command stop
    required: true
  resume:
    selector:
      entity:
        domain: button
        integration: proxmoxve
    name: Command resume
    required: true
  hibernate:
    selector:
      entity:
        domain: button
        integration: proxmoxve
    name: Command hibernate
    required: true
  reset:
    selector:
      entity:
        domain: button
        integration: proxmoxve
    name: Command reset
    required: true
sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{is_state( status, 'stopped') }}"
        sequence:
          - action: button.press
            metadata: {}
            data: {}
            target:
              entity_id: "{{ start }}"
      - conditions:
          - condition: template
            value_template: "{{is_state( status, 'suspended') or is_state( status, 'paused') }}"
        sequence:
          - action: button.press
            metadata: {}
            data: {}
            target:
              entity_id: "{{ resume }}"
      - conditions:
          - condition: template
            value_template: "{{is_state( status, 'running') }}"
        sequence:
          - action: button.press
            metadata: {}
            data: {}
            target:
              entity_id: "{{ hibernate }}"
    default:
      - action: button.press
        metadata: {}
        data: {}
        target:
          entity_id: "{{ reset }}"
```

Code for the card:
```
show_name: true
show_icon: false
type: button
tap_action:
  confirmation:
    text: Do you confirm the command execution?
  action: perform-action
  perform_action: script.vm_start_stop
  target: {}
  data:
    status: sensor.qemu_123_status
    start: button.qemu_123_start
    stop: button.qemu_123_stop
    resume: button.qemu_123_resume
    hibernate: button.qemu_123_hibernate
    reset: button.qemu_123_reset
name: VM Control
entity: sensor.qemu_123_status
show_state: true
hold_action:
  confirmation:
    text: Do you confirm the command execution?
  action: perform-action
  perform_action: button.press
  target:
    entity_id: button.qemu_123_shutdown
```
I believe this will do the job you want...

I believe you will find better help on the community forum: https://community.home-assistant.io/
