### ISSUE TITLE
Buttons don't to anything on version 2023.11 of HA

### ISSUE THREAD

**Issue by rVlad93** [dougiteixeira/proxmoxve#143]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

Buttons and everything shows up but the server doesn't react to any of the button presses anymore. Downgraded to previous version of HA and it's working fine.

### In which version of Home Assistant Core do you have the problem?

2023.11

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

8.0.4

**Comment by dougiteixeira** [comment]
Can you provide the debug logs? Include this in your config file:

```
logger:
  default: warning
  logs:
    custom_components.proxmoxve: debug
    proxmoxer: debug
```

After including this in your configuration file, try to execute some commands, save the log file and send it here, please.
