### ISSUE TITLE
Integration not ready yet

### ISSUE THREAD

**Issue by mokomonsen** [dougiteixeira/proxmoxve#24]
I just installed this, added true Hacs repository, clicked the integration link on from Github, set up and was able to log on to the Proxmox server and click of all my nodes. But after this I get a error on the integration, and my log shows as following: 
![image](https://user-images.githubusercontent.com/113433564/210568636-5574d74e-4d57-478d-813d-6f1293fef189.png)

Any advice? I tried to uninstall and reinstall, but that did not work

**Comment by svenger87** [comment]
Same here.

**Comment by dougiteixeira** [comment]
What version of Home Assistant are you using?

Can you provide the debug logs?  Include this in your config file:
```
logger:
  default: info
  logs:
    custom_components.proxmoxve: debug
    proxmoxer: debug
```
