### ISSUE TITLE
Config entry not ready yet

### ISSUE THREAD

**Issue by TheChristan** [dougiteixeira/proxmoxve#70]
Don't know whats wrong. It's probably an easy fix but can't seem to figure it out

```
Config entry 'pve - 192.168.0.125:8006' for proxmoxve integration not ready yet; Retrying in background
```

**Comment by dougiteixeira** [comment]
What version of Home Assistant are you using?

Can you provide the debug logs? Include this in your config file:

```
logger:
  default: warning
  logs:
    custom_components.proxmoxve: debug
    proxmoxer: debug
```
    
See if it's not a problem with the user's permissions, see more in #24.

**Comment by TheChristan** [comment]
It's a user error sorry. And is indeed with permissions I only had the permission PVEVMAdmin but had to add PVEAdmin and i can read out data. But what I can't seem to figure out is how to control it also. What permissions I give it it doesn't let me control it. Do you know what I did wrong and why this doesn't work. But thanks for this part!

**Comment by dougiteixeira** [comment]
> But what I can't seem to figure out is how to control it also.

What are you trying to control? What is the observed behavior?

Please send the debug logs report.

Can you provide the debug logs? Include this in your config file:
```
logger:
  default: warning
  logs:
    custom_components.proxmoxve: debug
    proxmoxer: debug
```
