### ISSUE TITLE
Node is not rediscovered once it was offline

### ISSUE THREAD

**Issue by rocktale** [dougiteixeira/proxmoxve#93]
I'm running version 2.0.0 of the plugin with Home Assistant 2023.6.0 (but the issue was already present with some of the previous versions of it) and it seems like the fix introduced with #42 does no longer work (at least for me). Maybe something was changed with the refactoring that went into the multi nodes setup in 2.0.0?

I have only one node configured that is not online all the time. When I reconfigure the integration it works like a charm. But once the node was offline and it comes back, all sensors show "unavailable" as if it was not there. Basically the same as when it was offline. I waited for at least half an hour but without any luck.

Would be nice if the integration could automatically detect that the node is back. Optimally, with a configurable retry interval.

**Comment by VeeeneX** [comment]
It's a bug but it has a workaround not a nice one but it works :D

I have a script called Reload proxmoxve:
```
alias: Reload Proxmox
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: state
    entity_id: binary_sensor.void
    state: "on"
action:
  - service: rest_command.reload_proxmoxve
    data: {}
mode: single
```

It calls rest_command that reload integration :sweat_smile: only when server is reachable over network and it does so every minute, you could preserve state somewhere to crate a simple State Machine and avoid repeated reloads but that's up to you. :)

**Comment by kumarunster** [comment]
same issue here

@VeeeneX could you share full example? where is the service 'rest_command.reload_proxmoxve' defined?

**Comment by VeeeneX** [comment]
Sure, this is my setup. But I like yours more :smile: 

```
rest_command:
  reload_proxmoxve:
    url: http://127.0.0.1:8123/api/config/config_entries/entry/89d77de9b91cb775b4bc24ceb646f208/reload
    method: POST
    headers:
      authorization: "Bearer <TOKEN>"
      accept: "application/json"
    content_type:  'application/json; charset=utf-8'
    verify_ssl: false
```
